config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'index#index'
  get '/event', to: 'index#get_events'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/browser.rb
class Browser < ActiveRecord::Base
  has_many :events
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :domain
  belongs_to :browser
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    @events = Event.select(:event_type).order(:event_type).distinct
    @browsers = Browser.all
    @domains = Domain.all
  end

  def get_events
    # getting params
    user_agent = params[:browser]
    domain = params[:domain]
    event_type = params[:event_type]
    date_start = params[:date_start]
    date_end = params[:date_end]
    group_date = (params[:group_date]).to_i
    group_hour = (params[:group_hour]).to_i
    group_event_type = (params[:group_event_type]).to_i
    group_browser = (params[:group_browser]).to_i
    group_domain = (params[:group_domain]).to_i

    # getting events depending on condition
    @events = Event.all
    @events = @events.where(event_type: event_type) unless event_type.blank?
    @events = @events.where(browser_id: user_agent) unless user_agent.blank?
    @events = @events.where(domain_id: domain) unless domain.blank?
    @events = @events.where("event_date <= '#{date_end}'") unless date_end.blank?
    @events = @events.where("event_date >= '#{date_start}'") unless date_start.blank?

    # grouping depending on checked checkboxes
    @grouped_events_by_date = group_date == 1 ? @events.group(:event_date).count : nil
    @grouped_events_by_hour = group_hour == 1 ? @events.group(:event_hour).count : nil
    @grouped_events_by_event_type = group_event_type == 1 ? @events.group(:event_type).count : nil
    @grouped_events_by_browser = group_browser == 1 ? @events.group(:browser).count : nil
    @grouped_events_by_domain = group_domain == 1 ? @events.group(:domain).count : nil

    respond_to do |format|
      format.html
      format.js
      format.json { render :json => {
          events: @events,
          grouped_by_date: @grouped_events_by_date,
          grouped_by_hour: @grouped_events_by_hour,
          grouped_by_event_type: @grouped_events_by_event_type,
          grouped_by_browser: @grouped_events_by_browser,
          grouped_by_domain: @grouped_events_by_domain
      }
      }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/events/_event.html.slim
tr
  td = event.event_type
  td = event.browser.name
  td = event.domain.name
  td = event.event_date
  td = event.event_hour
  td = event.counter

app/views/index/_grouped_by_browser.html.slim
- @grouped_events_by_browser.each do |event|
  tr
    td = event[0].name
    td = event[1]

app/views/index/_grouped_by_date.html.slim
- @grouped_events_by_date.each do |event|
  tr
    td = event[0]
    td = event[1]

app/views/index/_grouped_by_domain.html.slim
- @grouped_events_by_domain.each do |event|
  tr
    td = event[0].name
    td = event[1]

app/views/index/_grouped_by_event_type.html.slim
- @grouped_events_by_event_type.each do |event|
  tr
    td = event[0]
    td = event[1]

app/views/index/_grouped_by_hour.html.slim
- @grouped_events_by_hour.each do |event|
  tr
    td = event[0]
    td = event[1]

app/views/index/get_events.js.erb
<% if @events.length > 0 %>
  $("<%= escape_javascript(render @events) %>").appendTo(".report_events #events tbody");

  <% unless @grouped_events_by_date.nil? %>
    $("<%= escape_javascript(render partial: 'grouped_by_date', locals: @grouped_events_by_date) %>").appendTo("#table_group_date tbody");
  <% end %>

  <% unless @grouped_events_by_hour.nil? %>
    $("<%= escape_javascript(render partial: 'grouped_by_hour', locals: @grouped_events_by_hour) %>").appendTo("#table_group_hour tbody");
  <% end %>

  <% unless @grouped_events_by_event_type.nil? %>
    $("<%= escape_javascript(render partial: 'grouped_by_event_type', locals: @grouped_events_by_event_type) %>").appendTo("#table_group_event_type tbody");
  <% end %>

  <% unless @grouped_events_by_browser.nil? %>
    $("<%= escape_javascript(render partial: 'grouped_by_browser', locals: @grouped_events_by_browser) %>").appendTo("#table_group_browser tbody");
  <% end %>

  <% unless @grouped_events_by_domain.nil? %>
    $("<%= escape_javascript(render partial: 'grouped_by_domain', locals: @grouped_events_by_domain) %>").appendTo("#table_group_domain tbody");
  <% end %>
<% else %>
  $(".event-reporter-wrapper").after("<div class='no-content'><div class='container'><div class='row'><div class='col-md-12 col-xs-12'><h3>No content</h3></div></div></div></div>");
<% end %>

app/views/index/index.html.slim
.event-reporter-wrapper
  .container
    .row
      .col-md-12.col-xs-12
        .title
          .h1 Event Report
        .form-block
          = form_tag event_path, method: :get, remote: true, id: 'event_report_form' do
            .row
              .col-md-4.form-group
                = label_tag :date_start, 'Select start date'
                .input-group.date
                  = text_field_tag :date_start, nil, class: 'form-control type'
                  span.input-group-addon
                    span.glyphicon.glyphicon-calendar
              .col-md-4.form-group
                = label_tag :date_end, 'Select end date'
                .input-group.date
                  = text_field_tag :date_end, nil, class: 'form-control type'
                  span.input-group-addon
                    span.glyphicon.glyphicon-calendar
            .row
              .col-md-12.form-group
                = label_tag :browser, 'Select User-Agent'
                = select_tag :browser, options_from_collection_for_select(@browsers, "id", "name"), include_blank: '', class: 'form-control'
            .row
              .col-md-3.form-group
                = label_tag  :domain, 'Select domain'
                = select_tag :domain, options_from_collection_for_select(@domains, "id", "name"), include_blank: '', class: 'form-control'
              .col-md-3.form-group
                = label_tag :event_type, 'Select event type'
                = select_tag :event_type, options_from_collection_for_select(@events, "event_type", "event_type"), include_blank: '', class: 'form-control'
            .row
              .col-md-2.form-group
                .checkbox
                  = label_tag :group_date
                    = check_box_tag :group_date
                    | Group by date
              .col-md-2.form-group
                .checkbox
                  = label_tag :group_hour
                    = check_box_tag :group_hour
                    | Group by hour
              .col-md-2.form-group
                .checkbox
                  = label_tag :group_event_type
                    = check_box_tag :group_event_type
                    | Group by event type
              .col-md-2.form-group
                .checkbox
                  = label_tag :group_browser
                    = check_box_tag :group_browser
                    | Group by browser
              .col-md-2.form-group
                .checkbox
                  = label_tag :group_domain
                    = check_box_tag :group_domain
                    | Group by domain

            .row
              .col-md-6.form-group
                = submit_tag "Show Report"

    .report_events
      .container
        h3 Events report
        table.table.table-striped id="events"
          thead
            tr
              th Event type
              th Browser
              th Domain
              th Event date
              th Event hour
              th Counter
          tbody

    .group_date
      .container
        h3 Group by date
        table.table.table-striped id="table_group_date"
          thead
            tr
              th Date
              th Count
          tbody

    .group_hour
      .container
        h3 Group by hour
        table.table.table-striped id="table_group_hour"
          thead
            tr
              th Hour
              th Count
          tbody

    .group_event_type
      .container
        h3 Group by event type
        table.table.table-striped id="table_group_event_type"
          thead
            tr
              th Event type
              th Count
          tbody

    .group_browser
      .container
        h3 Group by browser
        table.table.table-striped id="table_group_browser"
          thead
            tr
              th Browser
              th Count
          tbody

    .group_domain
      .container
        h3 Group by domain
        table.table.table-striped id="table_group_domain"
          thead
            tr
              th Domain
              th Count
          tbody

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventReport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>